### ISSUE TITLE
expresiones booleanas

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-maetzy-quetzaly-angel-jesus#1]
[EXPRESIONES_BOOLEANAS.pdf](https://github.com/user-attachments/files/18066025/EXPRESIONES_BOOLEANAS.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:24/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:19.8
Califico Edwin Eduardo Mendoza Cruz

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
